title: Håndbok - Akademikerforbundet
description: Digital oppslarsverktøy
theme: just-the-docs

url: https://akademikerforbundet.github.io

aux_links:
  Template Repository: https://github.com/Akademikerforbundet/aka
