title: Håndbok - Akademikerforbundet
description: Digital oppslagsverktøy
theme: just-the-docs

url: https://akademikerforbundet.github.io
# repository: Akademikerforbundet/akademikerforbundet.github.io  # optional; remove if unsure

permalink: pretty

# Keep exclude lean
exclude:
  - .jekyll-cache/
  - node_modules/
  - vendor/

logo: "https://www.akademikerforbundet.no/grf/logo-rod.svg"

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

enable_copy_code_button: true

mermaid:
  version: "9.1.6"

heading_anchors: true

aux_links:
  "Til akademikerforbundet.no →": "https://akademikerforbundet.no"
aux_links_new_tab: false

nav_enabled: true
nav_sort: case_sensitive

# If you prefer these instead of aux_links, remove aux_links above
# nav_external_links:
#   - title: Til akademikerforbundet.no
#     url: https://akademikerforbundet.no

# Remove strict Liquid — it causes build errors with optional vars
# liquid:
#   error_mode: strict
#   strict_filters: true

back_to_top: true
back_to_top_text: "Til toppen"

footer_content: 'Copyright &copy; 2025 <a href="https://akademikerforbundet.no">Akademikerforbundet</a>'


# Only keep this if you actually add the compress plugin; otherwise omit
# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false
